name: table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 4.0.1
homepage: https://github.com/arkarmintun1/table_calendar

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.0
  simple_gesture_detector: ^0.2.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
